var userClickedPattern=[]; //to store user's pattern of colour
var gamePattern=[]; //to store computer's pattern
var level = 0; //starting
var start=false;
var buttonColours=['red','blue','green','yellow'];

$(document).keypress(function(e){
  // console.log(start + " "+ e.keyCode);
  if(start==false && e.keyCode==13){
    start=true;    //issue - this value of start is not changing in actual hence this code is running again and agian
    window.location.href="play.html";
  }
  else if(level==0){             //key press only when game starts
    $("#level-title").text("level "+ level);
    nextSequence();
  }
});

//to know what user has clicked
$(".btn").on("click",function(){
  var userChosenColor = $(this).attr('id'); //user clicked colour
  userClickedPattern.push(userChosenColor); //keeping track of user clicked colour

  playSound(userChosenColor);
  animatePress(userChosenColor);

  //checking
  checkAnswer(userClickedPattern.length - 1);
});

//it gives the next random colour
function nextSequence(){

  userClickedPattern=[]; //to clear the previous stored pattern of user
  ++level;
  $("#level-title").text("level "+ level);

  var randomNumber = Math.floor(Math.random() * 4);
  var randomChosenColor=buttonColours[randomNumber]; //generating random colour
  gamePattern.push(randomChosenColor);           //keeping track of colours generated by computer

  //effects on colour generated
  $("#"+randomChosenColor).fadeIn(100).fadeOut(100).fadeIn(100);
  //to play sound of that particular colour
  playSound(randomChosenColor);

}

function checkAnswer(currentLevel){
//checking last picked value of user's colour with computer stored colour pattern
  if(userClickedPattern[currentLevel]==gamePattern[currentLevel]){
    console.log("success");
    //if sequence gets completed then giving next random colour
    if(userClickedPattern.length==gamePattern.length){
      setTimeout(()=>{
        nextSequence();
      },1000);
    }
  }
  else{
    playSound("wrong");
    $("body").addClass("game-over");
    setTimeout(()=>{
      $("body").removeClass("game-over");
    },200);
    $("#level-title").text("Game Over, Press Any Key To Restart");
    //staring again
    restart();
  }
}

function restart(){
  level=0;
  gamePattern=[];
  start=true;
}

function playSound(name){
  var audio = new Audio("sounds/"+name+".mp3");
  audio.play();
}

function animatePress(currentColour){
    $("#"+currentColour).addClass("pressed");
    setTimeout(()=>{
      $("#"+currentColour).removeClass("pressed");
    },100);
}
